### PR TITLE
InfinispanEmbeddedProcessor doesn't filter out abstract class when lo…

### LINKED ISSUE #45: InfinispanEmbeddedProcessor doesn't filter out abstract class when loading SerializationContextInitializer
When InfinispanEmbeddedProcessor load all SerializationContextInitializer implementors, it doesn't filter out abstract classes
https://github.com/quarkiverse/quarkus-infinispan-embedded/blob/ad419177df96ee639ad38f6864923e0858de0be5/extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java#L120

and the setup fail when it tries to instantiate it:

https://github.com/quarkiverse/quarkus-infinispan-embedded/blob/ad419177df96ee639ad38f6864923e0858de0be5/extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java#L128

### PR DESCRIPTION
**Pull request by luigidemasi**
…ading SerializationContextInitializer

resolve #45

### CODE REVIEW

File: extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java [hunk 1]
```diff
@@ -123,6 +123,10 @@ ProtobufInitializers setup(BuildProducer<ReflectiveClassBuildItem> reflectiveCla
                 .addAll(index.getAllKnownImplementors(DotName.createSimple(GeneratedSchema.class.getName())));
         List<SerializationContextInitializer> initializers = new ArrayList<>(initializerClasses.size());
         for (ClassInfo ci : initializerClasses) {
+            if (ci.isAbstract()) {
+                // don't try to instantiate an abstract class...
+                continue;
```
Comment (karesti) [inline extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java:128]: oh nice catch @luigidemasi 
Would you like to add a test somewhere ?

Comment (luigidemasi) [reply extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java:128]: @karesti I added a test to cover this scenario, thanks for pointing it out. The test itself is simple, but I documented in the Javadoc what the issue was and how the fix is validated. Happy to adjust or expand if you think it would help.

Comment (karesti) [reply extension/deployment/src/main/java/io/quarkiverse/infinispan/embedded/deployment/InfinispanEmbeddedProcessor.java:128]: fantastic, I appreciate all the explanation there!

**Review by karesti — APPROVED** [review]
